### ISSUE TITLE
Doesn't work with FF 49.0.1

### ISSUE THREAD

**Issue by infomast** [bakulf/priv8#31]
a right click on a tab and choose a pre-defined sandboxed tab doesn't work.

**Comment by infomast** [comment]
In 49.0.2, the possibility to right clic on a tab and choose to open a priv8 tab has disappeared.

**Comment by darkpisto** [comment]
I have the same problem since 49.0.2, and the button priv8 disappeared too.

After desinstall priv8 (and purge all "priv8" in config:about) and reinstall : the button appeared again (but not the possibility to right clic on a tab and choose to open a priv8 tab) ... and the button disappeared on the next launch.

**Comment by bakulf** [comment]
my fault. sorry. Now the context menu is back in place. (version 0.1.4 in review)

**Comment by infomast** [comment]
Works fine now. Thanks!

**Comment by darkpisto** [comment]
@bakulf : Great job, thanks :)
